#!/bin/sh

cp -r \
  ./bat \
  ./btop \
  ./fish \
  ./foot \
  ./ghostty \
  ./hypr \
  ./lazygit \
  ./MangoHud \
  ./mpv \
  ./rustfmt \
  ./starship.toml \
  ./waybar \
  ./zellij \
  "$XDG_CONFIG_HOME"
cp -r ./cargo/* "$CARGO_HOME"
