#!/bin/sh

cp -r \
  "$XDG_CONFIG_HOME/bat/" \
  "$XDG_CONFIG_HOME/ghostty/" \
  "$XDG_CONFIG_HOME/git/" \
  "$XDG_CONFIG_HOME/lazygit/" \
  "$XDG_CONFIG_HOME/MangoHud/" \
  "$XDG_CONFIG_HOME/niri/" \
  "$XDG_CONFIG_HOME/mpv/" \
  "$XDG_CONFIG_HOME/rustfmt/" \
  "$XDG_CONFIG_HOME/starship.toml" \
  "$XDG_CONFIG_HOME/waybar/" \
  "$XDG_CONFIG_HOME/zellij/" \
  ./

cp -r \
  "$XDG_CONFIG_HOME/btop/btop.conf" \
  "$XDG_CONFIG_HOME/btop/themes/" \
  ./btop/

cp -r \
  "$XDG_CONFIG_HOME/fish/config.fish" \
  "$XDG_CONFIG_HOME/fish/conf.d/" \
  "$XDG_CONFIG_HOME/fish/functions/" \
  ./fish/

cp "$CARGO_HOME/config.toml" ./cargo/
cp "$CARGO_HOME/bin/cargo-inst" ./cargo/bin/
