#!/bin/sh

cp -r "$XDG_CONFIG_HOME"/bat/ ./
cp -r "$XDG_CONFIG_HOME"/btop/btop.conf "$XDG_CONFIG_HOME"/btop/themes/ ./btop/
cp "$XDG_CONFIG_HOME"/fish/config.fish ./fish/
cp -r "$XDG_CONFIG_HOME"/foot/ ./
cp -r "$XDG_CONFIG_HOME"/ghostty/ ./
cp -r "$XDG_CONFIG_HOME"/hypr/ ./
cp -r "$XDG_CONFIG_HOME"/lazygit/ ./
cp -r "$XDG_CONFIG_HOME"/MangoHud/ ./
cp -r "$XDG_CONFIG_HOME"/mpv/ ./
cp -r "$XDG_CONFIG_HOME"/rustfmt/ ./
cp "$XDG_CONFIG_HOME"/starship.toml ./
cp -r "$XDG_CONFIG_HOME"/waybar/ ./
cp "$CARGO_HOME"/config.toml ./cargo/
cp "$CARGO_HOME"/bin/cargo-inst ./cargo/bin/
cp -r "$XDG_CONFIG_HOME"/zellij/ ./
