theme = "catppuccin_mocha"

[editor]
scrolloff = 8
line-number = "relative"
cursorline = true
gutters = [
  "diagnostics",
  "spacer",
  "line-numbers",
  "spacer",
  "diff",
]
idle-timeout = 200
completion-trigger-len = 1
completion-replace = true
true-color = true
rulers = [80]
bufferline = "multiple"
color-modes = true

[editor.statusline]
left = [
  "mode",
  "spacer",
  "file-name",
  "version-control",
]
center = [
  "read-only-indicator",
]
right = [
  "spinner",
  "spacer",
  "diagnostics",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.smart-tab]
enable = true
