# Theme
theme = "gruvbox"

# Editor settings
[editor]
scrolloff = 8
line-number = "relative"
completion-trigger-len = 1
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-type", "file-name"]
right = ["diagnostics", "file-encoding", "file-line-ending", "selections", "position"]

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true
