theme = "rose_pine"

[editor]
scrolloff = 8
scroll-lines = 5
line-number = "relative"
cursorline = true
idle-timeout = 200
completion-trigger-len = 1
bufferline = "multiple"
color-modes = true
true-color = true

[editor.statusline]
left = [
  "mode",
  "spacer",
  "file-type",
  "file-name",
  "spacer",
  "version-control",
]
right = [
  "spinner",
  "spacer",
  "file-modification-indicator",
  "spacer",
  "diagnostics",
  "file-encoding",
  "file-line-ending",
  "selections",
  "position",
]
mode.normal = "normal"
mode.insert = "insert"
mode.select = "select"

[editor.cursor-shape]
normal = "block"
insert = "block"
select = "block"

[editor.file-picker]
hidden = true

[editor.indent-guides]
render = true

[editor.gutters]
line-numbers.min-width = 1

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
C-i = ":toggle lsp.display-inlay-hints"

[keys.insert]
C-i = ":toggle lsp.display-inlay-hints"

[keys.select]
C-i = ":toggle lsp.display-inlay-hints"
