[[language]]
name = "rust"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
'|' = '|'

[language-server.rust-analyzer.config]
check.command = "clippy"
check.allTargets = false
