[[language]]
name = "rust"

# https://github.com/helix-editor/helix/issues/8933
[[grammar]]
name = "gemini"

[grammar.source]
git = "https://git.sr.ht/~nbsp/tree-sitter-gemini/"
rev = "b60a42df3f76bd4e8f988465309d705a007dc506"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
'|' = '|'

[language-server.rust-analyzer.config]
check.command = "clippy"
check.allTargets = false
