[unstable]
profile-rustflags = true
gc = true

[alias]
in = "inst"
if = "info -v"
ber = "bench --profile release"
bei = "bench --profile _install"
br = "build --profile release"
bi = "build --profile _install"
rr = "run --profile release"
ri = "run --profile _install"
cl = "clean"
do = "doc --open"
nt = "nextest run"
ntr = "nextest run --cargo-profile release"
nti = "nextest run --cargo-profile _install"
ntm = "nextest run --profile default-miri"
ntl = "nextest list"
ar = "asm --simplify --profile release"
ai = "asm --simplify --profile _install"
sr = "size --profile release"
si = "size --profile _install"

[build]
rustc-wrapper = "sccache"

[profile.dev]
debug = "line-tables-only"

[profile.release]
incremental = false
opt-level = 3
codegen-units = 1
debug = "line-tables-only"
strip = false
lto = true

[profile._install]
inherits = "release"
rustflags = ["-Ctarget-cpu=native"]

[target.'cfg(all(target_arch = "x86_64", target_os = "linux"))']
rustflags = ["-Clink-arg=-fuse-ld=mold"]
