[unstable]
profile-rustflags = true
gc = true

[alias]
i = "inst"
in = "info -v"
be = "bench"
bep = "bench --profile _publish"
br = "b -r"
bp = "b --profile _publish"
bi = "b --profile _install"
rr = "r -r"
rp = "r --profile _publish"
ri = "r --profile _install"
cl = "clean"
do = "d --open"
t = "nextest run"
tr = "t -r"
tp = "t --cargo-profile _publish"
ti = "t --cargo-profile _install"
tl = "nextest list"
a = "ar --dev"
ar = "asm --simplify"
ap = "ar --profile _publish"
ai = "ar --profile _install"
u = "update"
s = "size"
sr = "s --release"
sp = "s --profile _publish"
si = "s --profile _install"

[build]
incremental = false
rustc-wrapper = "sccache"

[profile]
release = { opt-level = 3, strip = true }
_publish = { inherits = "release", codegen-units = 1, lto = true }
_install = { inherits = "_publish", rustflags = ["-Ctarget-cpu=native"] }

[target.'cfg(all())']
rustflags = ["-Zthreads=8"]

[target.'cfg(all(target_arch = "x86_64", target_os = "linux"))']
rustflags = ["-Clink-arg=-fuse-ld=mold"]
